Add new script "_n2038_snapper_echo_snapshot_description_by_id"

diff --git a/scripts/snapper/_n2038_snapper_echo_snapshot_description_by_id b/scripts/snapper/_n2038_snapper_echo_snapshot_description_by_id
--- a/scripts/snapper/_n2038_snapper_echo_snapshot_description_by_id
+++ b/scripts/snapper/_n2038_snapper_echo_snapshot_description_by_id
@@ -56,10 +56,8 @@
 
 # Imports
 source "./_n2038_error_if_snapper_is_not_installed"
-source "./n2038_snapper_list_configs"
 source "../sudo/_constants"
 source "../sudo/_n2038_update_sudo_rights"
-source "./_constants"
 
 # (REUSE) Prepare after imports
 {
@@ -72,33 +70,28 @@ source "./_constants"
   unset "source_previous_directory_$(get_text_hash "${BASH_SOURCE[*]}")" || exit "$?"
 }
 
-# Prints list of all snapshots for specified config
-# Argument 1: Config name
-function n2038_snapper_list_all() {
+# Print snapshot description for specified config with specified snapshot id
+function _n2038_snapper_echo_snapshot_description_by_id() {
   _n2038_error_if_snapper_is_not_installed || return "$?"
   _n2038_update_sudo_rights || return "$?"
 
-  local config="${1}" && shift
-  if [ -z "${config}" ]; then
-    echo "Usage: ${FUNCNAME[0]} <config name>" >&2
-    local list_of_available_configs
-    list_of_available_configs="$(n2038_snapper_list_configs | tr '\n' ' ')" || return "$?"
-    echo "Available configs: ${list_of_available_configs}" >&2
+  local config="${1}" && { shift || true; }
+  local snapshot_id="${1}" && { shift || true; }
+  if [ -z "${config}" ] || [ -z "${snapshot_id}" ]; then
+    echo "Usage: ${FUNCNAME[0]} <config> <snapshot_id>" >&2
     return 1
   fi
 
-  local column_name_1="${n2038_snapper_userdata_tag}_number"
-  # Use sudo here to get password before any output
+  local snapshot_description
   # shellcheck disable=SC2086
-  echo "============================================================"
-  echo "${column_name_1} │ date                │ description"
-  echo "============================================================"
+  snapshot_description="$(${n2038_sudo_prefix}snapper -c "${config}" list --columns number,description | sed -En "s/^${snapshot_id}\\s*[\\|│]\\s*(.+)\\s*\$/\\1/p")" || return "$?"
 
-  # "nl" to print line numbers
-  # shellcheck disable=SC2086
-  ${n2038_sudo_prefix}snapper -c "${config}" --iso list --columns number,date,description || return "$?"
+  if [ -z "${snapshot_description}" ]; then
+    echo "Snapshot not found!" >&2
+    return 1
+  fi
 
-  echo "============================================================"
+  echo "${snapshot_description}"
 
   return 0
 }
@@ -106,6 +99,6 @@ function n2038_snapper_list_all() {
 # Add the ability to execute this script by itself (for debugging)
 {
   if [ "${0}" == "${BASH_SOURCE[0]}" ]; then
-    n2038_snapper_list_all "${@}"
+    _n2038_snapper_echo_snapshot_description_by_id "${@}"
   fi
 }
