Add script to modify old snapshots for new id system

diff --git a/scripts/snapper/_n2038_snapper_echo_snapshot_description_by_n2038_id b/scripts/snapper/_n2038_snapper_echo_snapshot_description_by_n2038_id
--- a/scripts/snapper/_n2038_snapper_echo_snapshot_description_by_n2038_id
+++ b/scripts/snapper/_n2038_snapper_echo_snapshot_description_by_n2038_id
@@ -60,10 +60,6 @@ source "../sudo/_constants"
 source "../sudo/_n2038_update_sudo_rights"
 source "./_constants"
 source "./_n2038_error_if_snapper_is_not_installed"
-source "./_n2038_snapper_echo_snapshot_description_by_n2038_id"
-source "./_n2038_snapper_echo_snapshot_raw_id_by_n2038_number"
-source "./n2038_snapper_goto_raw_id"
-source "./n2038_snapper_list_configs"
 
 # (REUSE) Prepare after imports
 {
@@ -76,31 +72,28 @@ source "./n2038_snapper_list_configs"
   unset "source_previous_directory_$(get_text_hash "${BASH_SOURCE[*]}")" || exit "$?"
 }
 
-# Rollback specified config to specified snapshot n2038_number
-function f2038_snapper_goto_n2038_number() {
+# Print snapshot description for specified config with specified n2038_number
+function _f2038_snapper_echo_snapshot_description_by_n2038_id() {
   _f2038_error_if_snapper_is_not_installed || return "$?"
   _f2038_update_sudo_rights || return "$?"
 
-  local config="${1}" && shift
-  if [ -z "${config}" ]; then
-    echo "Usage: ${FUNCNAME[0]} <config> <n2038_number>" >&2
-    local list_of_available_configs
-    list_of_available_configs="$(f2038_snapper_list_configs | tr '\n' ' ')" || return "$?"
-    echo "Available configs: ${list_of_available_configs}" >&2
-    return 1
-  fi
-
-  local n2038_number="${1}" && shift
-  if [ -z "${n2038_number}" ]; then
+  local config="${1}" && { shift || true; }
+  local n2038_id="${1}" && { shift || true; }
+  if [ -z "${config}" ] || [ -z "${n2038_id}" ]; then
     echo "Usage: ${FUNCNAME[0]} <config> <n2038_number>" >&2
     return 1
   fi
 
-  local snapshot_id
-  snapshot_id="$(_f2038_snapper_echo_snapshot_raw_id_by_n2038_number "${config}" "${n2038_number}")" || return "$?"
-  echo "Snapshot ID: \"${snapshot_id}\"." >&2
+  local snapshot_description
+  # shellcheck disable=SC2086
+  snapshot_description="$(${n2038_sudo_prefix}snapper -c "${config}" list --columns userdata,description | sed -En "s/^n2038_id=${n2038_id}, tag=${n2038_snapper_userdata_tag}\\s*[\\|│]\\s*(.+)\\s*\$/\\1/p")" || return "$?"
 
-  f2038_snapper_goto_raw_id "${config}" "${snapshot_id}" || return "$?"
+  if [ -z "${snapshot_description}" ]; then
+    echo "Snapshot not found!" >&2
+    return 1
+  fi
+
+  echo "${snapshot_description}"
 
   return 0
 }
@@ -108,6 +101,6 @@ function f2038_snapper_goto_n2038_number() {
 # Add the ability to execute this script by itself (for debugging)
 {
   if [ "${0}" == "${BASH_SOURCE[0]}" ]; then
-    f2038_snapper_goto_n2038_number "${@}"
+    _f2038_snapper_echo_snapshot_description_by_n2038_id "${@}"
   fi
 }
